#!/bin/bash

cmd="./bin/toc"

usage() {
  cat << EOF >&2
Usage: ./test [-kdltC] [testname testname ...]
  -k keep: copy latest results to expected
  -d diff: show differences between latest results and expected
  -l list: list -lt files
  -t tree: tree files
  -C clean: remove latest results
  -I instructions: how to set up new tests
  -S suite: set the default test suite
EOF
  exit 1
}

# set the default suite (-S)
set_suite() {
echo $1 > "$TDS_FILE"
exit
}

get_suite() {
if test -e $TDS_FILE; then
	TS=`cat $TDS_FILE`
	echo "running test suite $TS"
else 
	echo "Use -S to set suite directory"
	exit 1
fi
}

instructions() {
  cat << EOF >&2
Setup:  To create a test suite...
	create a directory, its name is the suite name (TS below)
	create a subdirectory (folder) in TS with the test name <tn>
	in that folder:
		create a file of inputs, one line per input, named 'i'
		create a file with tiny-c or tiny-obj code for the test 't'
			[I use a soft link to the code stored elsewhere.]
	run './test -l <tn>' from two folders above your sub using your 
		test name
	run './test <tn>' to do the test, then ./test -l <tn> again. 
		that should produce the results files, r and d
		r has results (printf(...)), d has dumps (fprintf(stderr,...))
	Examine those two files. 
		If they look good run './test -k <tn>', (k for keep).
		Keep copies r and d to er and ed respectively, as expected results.
	(Notice you can set up tests that are expected to fail, hence capturing 
		dumps.)
EOF
  exit 1
}

# does one test
dotest() {
	bin/toc $TS/$1/t <$TS/$1/i >$TS/$1/r 2>$TS/$1/d
	echo TEST: $1 done
}
#does one keep
dokeep() {
	cp $TS/$1/r $TS/$1/er
	cp $TS/$1/d $TS/$1/ed
	echo KEEP: $1 done
}
#does one diff
dodiff() {
	FILE=./$TS/$1/r
	echo ----this run \< ----expected \> ---- diff $1 
	if [ -f $FILE ]; then
		FILE=./$TS/$1/er
		if [ -f $FILE ]; then
			diff $TS/$1/r $TS/$1/er
			diff $TS/$1/d $TS/$1/ed
		else
		   echo "File $FILE does not exist."
		fi
	else
		echo "File $FILE does not exist."
	fi
		
}
# removes d,r from one test
doclean() {
	rm -f $TS/$1/r
	rm -f $TS/$1/d
}
# list files of one test
dolist() {
	ls -lt $TS/$1
}
# tree files of one test
dotree() {
	tree $TS/$1 --noreport
}

# does one argument: just diff, just keep, or test and diff
doit() {
#	echo ~25testing: $kt $1
	if [ $clean = "YES" ]; then
		doclean $1
	elif [ $kt = "KEEP" ]; then
		dokeep $1
	elif [ $diff = "YES" ]; then
		dodiff $1
	elif [ $clean = "YES" ]; then
		doclean $1
	elif [ $list = "YES" ]; then
		dolist $1
	elif [ $tree = "YES" ]; then
		dotree $1
	else
		dotest $1
		dodiff $1
	fi
}

#do specific tests
dospecific() {
#	echo ~36do specific:
	for tname in $@
	do
		doit $tname
	done
}
doall(){
#	echo ~42do all:
	for tname in $( ls ./$TS ); do
		doit $tname
	done
}

#### MAIN ####
kt=test
diff=NO
clean=NO
list=NO
tree=NO
TDS_FILE="testDefaultSuite"
while getopts kdltISC o; do
  case $o in
    k) kt=KEEP;;
    d) diff=YES;;
	l) list=YES;;
	t) tree=YES;;
	I) instructions;;
	S) set_suite $2;;
	C) clean=YES;;
    *) usage;;
  esac
done
get_suite
shift "$((OPTIND - 1))"

if [ $# -gt 0 ]; then
    dospecific $@
else
	doall
fi
